[features]
seeds = false
[programs.localnet]
mysolanaapp = "3qQYTQ4Twbzw7eNDcTdTNnJ7w5WWZnSjddW74bDkjvyz"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/cryptodev96/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
